### ISSUE TITLE
text in debugging practice should be changed

### ISSUE THREAD

**Issue by seanreed1111** [learn-co-curriculum/objc-cartoon-collections#6]
Under Jerry Mouse, the text says

...then the method should return *nil* so Jerry knows to look somewhere else.

This does not match the test.

Text should say:

...then the method should return "No premium cheeses in stock." so Jerry knows to look somewhere else.

**Comment by markedwardmurray** [comment]
:+1: I'm gonna have to ask about a way to give you karma for pointing out these kinds of things.

**Comment by seanreed1111** [comment]
thanks! if karma == beer, that works, too...
